name: Version Bump Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  version-check:
    name: Version Info
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get PR Labels
        id: pr_labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            console.log("Found PR labels:", labels);
            core.setOutput('labels', labels.join(','));

      - name: Check for Conventional Commit Messages
        id: check_commits
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Checking commits for PR #$PR_NUMBER"
          
          COMMITS=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/commits --jq '.[].commit.message')
          
          echo "Commit messages:"
          echo "$COMMITS"
          
          if echo "$COMMITS" | grep -qE "(feat|fix|BREAKING CHANGE)"; then
            echo "conventional_commit=true" >> $GITHUB_OUTPUT
            echo "Found conventional commit pattern"
          else
            echo "conventional_commit=false" >> $GITHUB_OUTPUT
            echo "No conventional commit pattern found"
          fi

      - name: Verify Version Information
        id: verify_version
        if: steps.pr_labels.outputs.labels == '' && steps.check_commits.outputs.conventional_commit == 'false'
        run: |
          echo "::error::Missing version bump information in both PR labels and commit messages"
          exit 1  # This will cause the check to fail
          
      - name: Notify Missing Version Info
        if: failure() && steps.verify_version.conclusion == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "🚨 **Missing Version Bump Information** 🚨\n\nPlease add one of the following:\n- A PR label (`major`, `minor`, or `patch`)\n- A conventional commit message (e.g., `feat:`, `fix:`, or `BREAKING CHANGE:`).\n\nThis is required to determine the version bump for the release."
            });